name: Palletforce Shopify Sync

on:
  schedule:
    - cron: "*/2 * * * *"   # Every 1 hour
    
  workflow_dispatch:     # Manual run button

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Palletforce sync
        run: node index.js
        env:
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          SHOPIFY_API_VERSION: 2024-01
          PALLETFORCE_URL: https://apiuat.palletforce.net/api/ExternalScanning/DownloadTracking
          PALLETFORCE_ACCESS_KEY: ${{ secrets.PALLETFORCE_ACCESS_KEY }}
